# Generated by Django 4.2.11 on 2024-04-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_score', models.PositiveIntegerField(verbose_name='№ счета')),
                ('first_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='День рождения')),
                ('inn', models.PositiveIntegerField(verbose_name='ИНН')),
                ('user', models.CharField(max_length=120, verbose_name='ФИО ответсвенного')),
                ('slug', models.SlugField(max_length=60, verbose_name='URL')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
            },
        ),
    ]
